/* eslint-disable */
// WARNING: Do not edit this file

const ebconfig = {
  "integration": "project-ue-ai-project-6xc2zfzYpOQZgGsChX8-3X2QYFzgAJgq",
  "version": "2020-11-20"
}

export default ebconfig;